stages:
  - build
  - test

image: debian:12-slim

variables:
  ONNX_VERSION: "1.17.3"

.apt_setup:
  before_script:
    - rm -f /etc/apt/sources.list
    - rm -rf /etc/apt/sources.list.d/*
    - echo "deb http://mirror.selectel.ru/debian bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list
    - echo "deb http://mirror.selectel.ru/debian bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list
    - apt-get update

default:
  cache: &global_cache
    - key: onnxruntime-${ONNX_VERSION}
      paths:
        - onnxruntime.tgz
        - onnxruntime-linux-x64-${ONNX_VERSION}/

build:
  stage: build
  before_script:
    - !reference [.apt_setup, before_script]
    - |
      apt-get install -y \
        build-essential \
        pkg-config \
        curl \
        git \
        ca-certificates \
        libpcre2-dev \
        zlib1g-dev \
        libssl-dev

    # ONNX Runtime
    - |
      if [ ! -f onnxruntime.tgz ]; then
        curl -L -o onnxruntime.tgz \
          https://github.com/microsoft/onnxruntime/releases/download/v${ONNX_VERSION}/onnxruntime-linux-x64-${ONNX_VERSION}.tgz
      fi
    - |
      if [ ! -d onnxruntime-linux-x64-${ONNX_VERSION} ]; then
        tar -xzf onnxruntime.tgz
      fi
    - cp -r onnxruntime-linux-x64-${ONNX_VERSION}/include/* /usr/local/include/
    - cp -r onnxruntime-linux-x64-${ONNX_VERSION}/lib/* /usr/local/lib/
    - ldconfig

    - |
      export NGINX_VERSION=$(apt-cache show nginx \
        | grep -m1 '^Version:' \
        | grep -oP '\d+\.\d+\.\d+')
    - curl -LO http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz  
    - tar -xzf nginx-${NGINX_VERSION}.tar.gz
    - mv nginx-${NGINX_VERSION} nginx

  script:
    - cd nginx
    - |
      ./configure \
      --add-dynamic-module=.. \
      --with-ld-opt="-Wl,-rpath,/usr/local/lib" \
      --with-compat
    - make modules

  artifacts:
    paths:
      - nginx/objs/*.so

test:
  stage: test
  dependencies:
    - build
  cache:
    - *global_cache
    - key: model
      paths:
        - model.onnx
  before_script:
    - !reference [.apt_setup, before_script]
    - apt-get install -y curl ca-certificates nginx

    - cp -r onnxruntime-linux-x64-${ONNX_VERSION}/lib/* /usr/local/lib/
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - ldconfig

    - |
      if [ ! -f model.onnx ]; then
        curl -L -o model.onnx \
        https://github.com/onnx/models/raw/main/validated/vision/classification/squeezenet/model/squeezenet1.0-3.onnx
      fi
    - cp model.onnx /etc/nginx/model.onnx

    - mkdir -p /tmp/nginx-modules
    - cp nginx/objs/ngx_http_ml_ddos_module.so /tmp/nginx-modules/

    - mkdir -p /etc/nginx/logs
    - |
      cat > /etc/nginx/nginx.conf <<EOF
      load_module /tmp/nginx-modules/ngx_http_ml_ddos_module.so;

      events {}

      error_log /etc/nginx/logs/error.log info;

      http {
          server {
              listen 8080;

              location /test {
                  ngx_http_ml_ddos;
                  return 200 "OK\n";
              }
          }
      }
      EOF
  script:
    - nginx -v
    - nginx -t 
    - nginx

    - |
      for i in $(seq 1 20); do
        curl -s http://127.0.0.1:8080/test && break
        sleep 1
      done
    - curl -i http://127.0.0.1:8080/test

    - nginx -s stop
