stages:
  - build
  - test

image: debian:12-slim

variables:
  NGINX_VERSION: "1.30.0"

.apt_setup:
  before_script:
    - rm -f /etc/apt/sources.list
    - rm -rf /etc/apt/sources.list.d/*
    - echo "deb http://mirror.selectel.ru/debian bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list
    - echo "deb http://mirror.selectel.ru/debian bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list
    - apt-get update

build:
  stage: build
  before_script:
    - !reference [.apt_setup, before_script]
    - |
      apt-get install -y \
        build-essential \
        clang \
        pkg-config \
        curl \
        git \
        ca-certificates \
        libpcre2-dev \
        zlib1g-dev \
        libssl-dev

    # ONNX Runtime
    - curl -L -o onnxruntime.tgz https://github.com/microsoft/onnxruntime/releases/download/v1.17.3/onnxruntime-linux-x64-1.17.3.tgz
    - tar -xzf onnxruntime.tgz
    - cp -r onnxruntime-linux-x64-1.17.3/include/* /usr/local/include/
    - cp -r onnxruntime-linux-x64-1.17.3/lib/* /usr/local/lib/
    - ln -sf /usr/local/lib/libonnxruntime.so /usr/local/lib/libonnxruntime.so.1
    - ldconfig

    - mkdir -p /usr/local/lib/pkgconfig
    - |
      cat > /usr/local/lib/pkgconfig/libonnxruntime.pc <<EOF
      prefix=/usr/local
      exec_prefix=\${prefix}
      libdir=\${prefix}/lib
      includedir=\${prefix}/include

      Name: onnxruntime
      Description: ONNX Runtime C API
      Version: 1.17.3
      Libs: -L\${libdir} -lonnxruntime
      Cflags: -I\${includedir}
      EOF

    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
    - pkg-config --cflags libonnxruntime
    - pkg-config --libs libonnxruntime

    - curl -LO http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
    - tar -xzf nginx-${NGINX_VERSION}.tar.gz
    - mv nginx-${NGINX_VERSION} nginx

  script:
    - cd nginx
    - ./configure --add-dynamic-module=.. --with-ld-opt="-Wl,-rpath,/usr/local/lib"
    - make modules

  artifacts:
    paths:
      - nginx/objs/*.so

test:
  stage: test
  dependencies:
    - build
  before_script:
    - !reference [.apt_setup, before_script]
    - apt-get install -y nginx curl ca-certificates

    - mkdir -p /tmp/nginx-modules
    - cp nginx/objs/ngx_http_ml_ddos_module.so /tmp/nginx-modules/

    - |
      cat > /etc/nginx/nginx.conf <<EOF
      load_module /tmp/nginx-modules/ngx_http_ml_ddos_module.so;

      events {}

      http {
          server {
              listen 8080;

              location /test {
                  ngx_http_ml_ddos /etc/nginx/model.onnx;
                  return 200 "OK\n";
              }
          }
      }
      EOF

    - echo "dummy" > /etc/nginx/model.onnx
    - export LD_LIBRARY_PATH=/usr/local/lib:$
    - ls /usr/local/lib
    - ldconfig
  script:
    - nginx

    - sleep 1
    - curl -i http://127.0.0.1:8080/test

    - nginx -t
    - nginx -s stop
